//! Raw FFI bindings to the Modular MAX C API.
//!
//! Generated by bindgen from the headers in `max/include/max/c/`.
//! These are opaque-struct-based bindings — you interact through
//! function pointers, not by reading struct fields directly.
//!
//! For a safe, ergonomic API, use `mojo-bridge` instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
